theme: jekyll-theme-chirpy
lang: pt-BR
timezone: America/Sao_Paulo
title: Códigos Aleatórios 2
tagline: Reflexões sobre programação, carreira e muitos tutoriais
github:
  username: erickamaro
social:
  name: Erick
  email: erickamaroamaro@gmail.com
  links:
    - https://github.com/erickamaroamaro
    - https://www.linkedin.com/in/erick-gabriel-amaro
avatar: ./images/java-chan.jpeg
paginate: 10
